config/routes.rb
Rails.application.routes.draw do
  
  resources :final
  resources :toys

  root to: "final#index"

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  has_one :user
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  has_many :toyfeatures
  has_many :toypictures
  

end

app/models/toyfeature.rb
class Toyfeature < ActiveRecord::Base
  has_and_belongs_to_many :toys
end

app/models/toypicture.rb
class Toypicture < ActiveRecord::Base
end

app/models/toyreview.rb
class Toyreview < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/final_controller.rb
class FinalController < ApplicationController

  def index
    @toys = Toy.all
    @users = User.all
    @dogs = Dog.all
    @toyreviews = Toyreview.all
    @toyfeatures = Toyfeature.all
    
  end

 
  
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController

  def index
    @toys = Toy.all
    @users = User.all
    @dogs = Dog.all
    @toyreviews = Toyreview.all
    @toyfeatures = Toyfeature.all
  end

  def show
    @toy = Toy.find_by(id: params["id"])
    @toyreview = Toyreview.find_by(toy_id: @toy.id)
    @toyfeature = Toyfeature.find_by(toy_id: @toy.id)
    @dogsfavorite = Dog.find_by(favorite_toy_id1: @toy.id)
  end

 


  def edit
    @toy = Toy.find_by(id:params["id"])
  end

  def update
    toy_params = params.require(:toy).permit(:name, :short_description, :long_description, :link_to_buy, :brand, :good_for)
    @toy = Toy.find_by(id: params["id"])
    @toy.update(toy_params)
    redirect_to toy_path
  end

  def new
    @toy = Toy.new
  end

  def create
    toy_params = params.require(:toy).permit(:name, :short_description, :long_description, :link_to_buy, :brand, :good_for)
    Toy.create(toy_params)
    #render :text => toy_params
    redirect_to toy_path
  end

  def destroy
    
    @toy = Toy.find_by(id: params["id"])
    @toy.destroy
    redirect_to toy_path

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/final/index.html.erb
<h2>Final Project!</h2>
<br>
<p><i>
This project is a webapp that is like Yelp for dog toys. Too often, owners of dogs are frustrated when they purchase a dog toy only to have their pooch reject it or tear it to shreds in 2 minutes. The online reviews at sites do a poor job because I can't compare their dog to mine. This webapp will have the users submit reviews and characteristics of their dogs so that each person will get a tailored recommendation for their pet. For instance, a hyperactive golden retriever might tear something to shreds and their owner would post a negative review. However, for my gentle beagle, that toy might be the best. Eventually, I want to adjust people's reviews (like netflix) to make approriate recommendations for the individual dog.</i></p><br>


<h3><%=link_to "Here are all the toys (WEEK 6 HOMEWORK)", toys_path%></h3>


<h3>Here are all the toy reviews:</h3>
<p>
<% @toyreviews.each do |toyreview| %>
  
  <%= toyreview.id %>: <%= toyreview.review%><br>
<%end%>
</p>

<h3>Here are all the dogs:</h3>
<p>
<% @dogs.each do |dog| %>
  
  <%= dog.id %>: <%= dog.name%><br>
<%end%>
</p>

<h3>Here are all the users:</h3>
<p>
<% @users.each do |user| %>
  
  <%= user.id %>: <%= user.username%>, dog's name is: <%= @dogs.find_by(id: user.dog_id1).name%><br>
<%end%>
</p>

app/views/final/show.html.erb
<table class="table table-hover">
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  <tr>

  <tr>
    <td>id</td>
    <td><%=@toy.id%></td>
  </tr>

  <tr>
    <td>name</td>
    <td><%=@toy.name%></td>
  </tr>

  <tr>
    <td>short_description</td>
    <td><%=@toy.short_description%></td>
  </tr>

  <tr>
    <td>long_description</td>
    <td><%=@toy.long_description%></td>
  </tr>

  <tr>
    <td>link_to_buy</td>
    <td><%=@toy.link_to_buy%></td>
  </tr>

  <tr>
    <td>brand</td>
    <td><%=@toy.brand%></td>
  </tr>

  <tr>
    <td>good_for</td>
    <td><%=@toy.good_for%></td>
  </tr>

  <tr>
    <td>toy review</td>
    <td><%=@toyreview.review%></td>
  </tr>

  <tr>
    <td>durability</td>
    <td><%=@toy.durability%></td>
  </tr>

  <tr>
    <td>Toyfeatures</td>
    <td><%=@toyfeature.feature1%><br> 
    <%=@toyfeature.feature2%><br>
    <%=@toyfeature.feature3%><br>
    <%=@toyfeature.feature4%><br>
    <%=@toyfeature.feature5%><br>
    </td>
  </tr>

  <tr>
    <td>This dog loves this toy</td>
    <td><%=@dogsfavorite.name%> owned by <%=User.find_by(dog_id1: @dogsfavorite.id).username%>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/toys/edit.html.erb
<h3><%=link_to "Back to the list of Toys", toys_path%></h3><br>
<%= form_for @toy do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :short_description %>
    <%= form.text_field :short_description, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :long_description %>
    <%= form.text_field :long_description, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :link_to_buy %>
    <%= form.text_field :link_to_buy, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :good_for %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Xtra Small Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Small Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Medium Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Large Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Xtra Large Dogs") %>

  </div> 

  <div class="form-group">
    <%= form.label :durability %>
    <%= form.text_field :durability, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :good_for_pet_size %>
    <%= form.text_field :good_for_pet_size, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :color %>
    <%= form.text_field :color, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :material %>
    <%= form.text_field :material, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div> 

  <%= form.button 'Update Toy', class: "btn btn-success" %>
<% end %>

app/views/toys/index.html.erb
<p>
<%= link_to "New Toy", new_toy_path, class: 'btn btn-sm btn-success' %></p>
<p>
<table class="table table-bordered">
<% @toys.each do |toy| %>
  <tr>
  <td><%=link_to toy.id, toy_path(toy)%></td>
  <td><%= link_to toy.name, toy_path(toy)%></td>
  <td><%=link_to "edit",edit_toy_path(toy)%></td>
  <td><%=link_to "Delete",toy_path(toy),method: :delete, data: { confirm: 'Are you sure??!?' } %></td>
  </tr>
<%end%>
</table>
</p>

app/views/toys/new.html.erb
<h3><%=link_to "Back to the list of Toys", toys_path%></h3><br>

<%= form_for @toy do |form| %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :short_description %>
    <%= form.text_field :short_description, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :long_description %>
    <%= form.text_field :long_description, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :link_to_buy %>
    <%= form.text_field :link_to_buy, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :good_for %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Xtra Small Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Small Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Medium Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Large Dogs") %>
    <%= check_box_tag(:good_for) %>
    <%= label_tag(:good_for, "Xtra Large Dogs") %>

  </div> 

  <div class="form-group">
    <%= form.label :durability %>
    <%= form.text_field :durability, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :good_for_pet_size %>
    <%= form.text_field :good_for_pet_size, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :color %>
    <%= form.text_field :color, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :material %>
    <%= form.text_field :material, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div> 

  <%= form.button 'Create New Toy', class: "btn btn-success" %>
<% end %>

app/views/toys/show.html.erb
<h3><%=link_to "Edit Toy",edit_toy_path(@toy)%></h3><br>
<h3><%=link_to "Back to the list of Toys", toys_path%></h3>
<br>

<table class="table table-hover">
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  <tr>

  <tr>
    <td>id</td>
    <td><%=@toy.id%></td>
  </tr>

  <tr>
    <td>name</td>
    <td><%=@toy.name%></td>
  </tr>

  <tr>
    <td>short_description</td>
    <td><%=@toy.short_description%></td>
  </tr>

  <tr>
    <td>long_description</td>
    <td><%=@toy.long_description%></td>
  </tr>

  <tr>
    <td>link_to_buy</td>
    <td><%=link_to "Amazon", @toy.link_to_buy%></td>
  </tr>

  <tr>
    <td>brand</td>
    <td><%=@toy.brand%></td>
  </tr>

  <tr>
    <td>good_for</td>
    <td>
      <li><input type="checkbox"> Xtra Small Dogs</li>
      <li><input type="checkbox"> Small Dogs</li>
      <li><input type="checkbox"> Medium Dogs</li>
      <li><input type="checkbox"> Large Dogs</li>
      <li><input type="checkbox"> Xtra Large Dogs</li>
      <li><%=@toy.good_for%></li>
    </td>
  </tr>

  <tr>
    <td>toy review</td>
    <td><%=@toyreview.review%></td>
  </tr>

  <tr>
    <td>durability</td>
    <td><%=@toy.durability%></td>
  </tr>

  <tr>
    <td>Toyfeatures</td>
    <td><%=@toyfeature.feature1%><br> 
    <%=@toyfeature.feature2%><br>
    <%=@toyfeature.feature3%><br>
    <%=@toyfeature.feature4%><br>
    <%=@toyfeature.feature5%><br>
    </td>
  </tr>

  <tr>
    <td>This dog loves this toy</td>
    <td><%=@dogsfavorite.name%> owned by <%=User.find_by(dog_id1: @dogsfavorite.id).username%>
    </td>
  </tr>
</table>